# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/RohanS/Desktop/lab6_1_new/lab6_1_new.srcs/sources_1/ip/bg_rom/bg_rom.xci
# IP: The module: 'bg_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/RohanS/Desktop/lab6_1_new/lab6_1_new.gen/sources_1/ip/bg_rom/bg_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bg_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/RohanS/Desktop/lab6_1_new/lab6_1_new.srcs/sources_1/ip/bg_rom/bg_rom.xci
# IP: The module: 'bg_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/RohanS/Desktop/lab6_1_new/lab6_1_new.gen/sources_1/ip/bg_rom/bg_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bg_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
